--- #YAML:1.0
name:                Email-Thread
version:             0.711
abstract:            Use JWZ's mail threading algorithm with Email::Simple objects
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Mail::Thread:                  2.4
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Iain Truskett <spoon@cpan.org>
