# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Thread
version:      0.71
version_from: lib/Email/Thread.pm
installdirs:  site
requires:
    Mail::Thread:                  2.4
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
