--- #YAML:1.0
build_requires:
  Test::More: 0.47
conflicts: {}
distribution_type: module
license: perl
name: Email-Thread
recommends:
requires:
  Mail::Thread: 2.1
version: 0.66
generated_by: docmaker version 0.89
