#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Thread
version:      0.65
version_from: lib/Email/Thread.pm
installdirs:  site
requires:
    Test::More:                    0.47
    Mail::Thread:                  2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_02
